### ISSUE TITLE
Would love an easier to understand example

### ISSUE THREAD

**Issue by Pebaz** [ekzhang/ukanren-rs#1]
As someone who does not have any familiarity with the concepts put forth in this crate, it would be awesome to have an even simpler example on the front page of the repo because I quite literally have no idea what the current example means. =)

**Comment by ekzhang** [comment]
Sorry about that! I updated the README to link to the µKanren [paper](http://webyrd.net/scheme-2013/papers/HemannMuKanren2013.pdf) instead of the GitHub repository, which doesn't provide much info. If you're looking to get started with relational programming, check out the [miniKanren website](http://minikanren.org/)! The appendo example comes from [this ICFP 2017 artifact](https://io.livecode.ch/learn/gregr/icfp2017-artifact-auas7pp).

I see on your profile that you've done some work with Nim before, and I was actually thinking about implementing a similar language in Nim, but decided on Rust first since I was more familiar with it. I think it might work really well though, especially since Nim has the iterator `yield` syntax and garbage collection! (And it doesn't exist yet, see https://github.com/nim-lang/needed-libraries/issues/88.)

**Comment by Pebaz** [comment]
Awesome thank you for the info!
Yes Nim is a fantastic candidate for this :)
